Lesson 05
HelenMaksimova/geekshop pull request #5
Opened 2021-07-07 20:14 UTC by HelenMaksimova

Я добавила в профиль поле Дата рождения. Но виджет DataInput имеет тип текст. Конечно, меня это не очень устроило и я прописала это поле в модели формы вот так:

birthday = forms.DateField(widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control py-4'}), required=False)

И всё бы ничего. Когда дата рождения не заполнена, отображается всё красиво, данные заносятся нормально, в базу приходят... Вот только обратно в форму в это поле дата рождения из базы не выводится. То есть она загружается, в объекте user она есть, а на странице пустое поле ввода даты - дд.мм.гг. Если убрать тип date в DataInput, всё отображается, но в текстовом поле. 

Вот на этом моменте я сейчас остановилась. Пока буду делать дальше, потом внесу изменения, если получится решить проблему, или просто исправлю виджет в поле на текстовый тип.

2021-07-08 09:18 UTC, HelenMaksimova commented
Задание доделано, кроме вышеописанного момента с полем для даты рождения. Возможно, перемудрила с методами для классов, написала свои теги для того, чтобы можно было передать аргумент с пользователем для фильтрации. Не уверена, что это оправдано. Но оно работает.

2021-07-09 08:26 UTC, Vokler requested changes

2021-07-09 08:26 UTC, Vokler commented on users/forms.py
> +    birthday = forms.DateField(widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control py-4'}), required=False)
Так как `type=date` должен содержать в value в input определенный формат, то этот формат нужно добавить и сюда.
Болше инфо про `type=date` https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date.

Исправить можно следующим образом:
```
birthday = forms.DateField(widget=forms.DateInput(attrs={
        'type': 'date', 'class': 'form-control py-4'}, format=('%Y-%m-%d')), required=False)
```

2021-07-09 10:16 UTC, HelenMaksimova commented on users/forms.py
> +    birthday = forms.DateField(widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control py-4'}), required=False)
Исправила! Спасибо огромное)

2021-07-12 08:21 UTC, Vokler approved these changes

2021-07-12 08:21 UTC, merged